/**
 * neural_echo_ffi.h
 *
 * Auto-generated by cbindgen from neural_echo_ffi/src/lib.rs
 * DO NOT EDIT — regenerated automatically during Rust build.
 *
 * This stub file allows C++ to compile before the Rust build has run.
 * The actual header is written to this location by build.rs via cbindgen.
 */

#ifndef NEURAL_ECHO_FFI_H
#define NEURAL_ECHO_FFI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Status codes returned by neural runtime FFI functions.
 */
typedef enum NeuralStatus {
    NeuralStatus_Ok           = 0,
    NeuralStatus_QueueFull    = 1,
    NeuralStatus_MaskNotReady = 2,
    NeuralStatus_InitFailed   = 3,
    NeuralStatus_NullPointer  = 4,
} NeuralStatus;

/**
 * Opaque neural inference context.
 * Created by ne_context_create(), destroyed by ne_context_destroy().
 */
typedef struct NeuralContext NeuralContext;

/**
 * Create a NeuralContext and load the ONNX model.
 *
 * @param config_path  Null-terminated path to neural_echo.toml.
 *                     Pass NULL to use built-in defaults.
 * @return             Heap-allocated context, or NULL on failure.
 */
NeuralContext *ne_context_create(const char *config_path);

/**
 * Destroy a NeuralContext.
 * Safe to call with NULL.
 */
void ne_context_destroy(NeuralContext *ctx);

/**
 * Run neural inference for one spectral frame.
 *
 * @param ctx                Non-null context from ne_context_create().
 * @param far_spectrum       [freq_bins] far-end magnitude spectrum (float32).
 * @param mic_spectrum       [freq_bins] microphone magnitude spectrum (float32).
 * @param residual_spectrum  [freq_bins] residual echo magnitude spectrum (float32).
 * @param mask_out           [freq_bins] output suppression mask written here.
 * @return                   NeuralStatus_Ok on success.
 */
NeuralStatus ne_process_frame(NeuralContext       *ctx,
                               const float        *far_spectrum,
                               const float        *mic_spectrum,
                               const float        *residual_spectrum,
                               float              *mask_out);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* NEURAL_ECHO_FFI_H */
